name: Deploy to Production

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug SSH connection
      run: ssh -v -i ~/.ssh/id_rsa deploy@162.243.186.231


    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Adjust to your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Deploy to production
      run: cap production deploy
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
