name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 3.2.2 # Adjust the Ruby version as needed

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Deploy to Production
      run: cap production deploy
